/**
 * C# code generator — classes with DataAnnotation validation attributes.
 */

import type { SchemaFieldType, SchemaField } from '@odin-foundation/core';
import type { ParsedSchemaFile, ResolvedType } from '../types.js';
import { typeNameToInterface, getTypeNameFromRef, resolveType, findTypeSource, calculateRelativePath } from '../codegen.js';

function odinTypeToCS(type: SchemaFieldType, localTypes: Set<string>): string {
  switch (type.kind) {
    case 'string': return 'string';
    case 'boolean': return 'bool';
    case 'number': case 'currency': case 'percent': case 'decimal': return 'decimal';
    case 'integer': return 'long';
    case 'date': return 'DateOnly';
    case 'timestamp': return 'DateTimeOffset';
    case 'time': return 'TimeOnly';
    case 'duration': return 'TimeSpan';
    case 'binary': return 'byte[]';
    case 'null': return 'object';
    case 'reference': {
      if (!type.targetPath) return 'object';
      const name = typeNameToInterface(getTypeNameFromRef(type.targetPath));
      return localTypes.has(name) ? name : 'object';
    }
    case 'typeRef': {
      const name = typeNameToInterface(getTypeNameFromRef(type.name));
      return localTypes.has(name) ? name : 'object';
    }
    case 'enum': return 'string';
    case 'union': return 'object';
    default: return 'object';
  }
}

function csType(type: SchemaFieldType, required: boolean, nullable: boolean, isArray: boolean, localTypes: Set<string>): string {
  const baseType = odinTypeToCS(type, localTypes);
  if (isArray) return `List<${baseType}>`;
  if (nullable || (!required && !['string', 'byte[]', 'object'].includes(baseType))) return `${baseType}?`;
  return baseType;
}

function generateClass(resolved: ResolvedType, localTypes: Set<string>): string {
  const lines: string[] = [];
  lines.push(`public class ${resolved.interfaceName}`);
  lines.push('{');

  for (const [fieldName, { field, isArray }] of resolved.fields) {
    const attrs: string[] = [];
    if (field.required) attrs.push('    [Required]');
    if (field.redacted) attrs.push('    // Confidential field');

    for (const attr of attrs) lines.push(attr);

    let propName = fieldName.charAt(0).toUpperCase() + fieldName.slice(1);
    // C# doesn't allow property name == enclosing type name
    if (propName === resolved.interfaceName) propName += 'Value';
    const type = csType(field.type, field.required, field.nullable, isArray, localTypes);
    lines.push(`    public ${type} ${propName} { get; set; }`);
    lines.push('');
  }

  lines.push('}');
  return lines.join('\n');
}

export function generateCSharp(
  parsed: ParsedSchemaFile,
  allSchemas: Map<string, ParsedSchemaFile>
): string {
  const lines: string[] = [];
  const title = parsed.schema.metadata.title ?? parsed.namespaceId;
  // Full path namespace including filename to avoid collisions
  const nsParts = parsed.outputPath.replace(/\.ts$/, '').split('/');
  if (nsParts.length === 0) nsParts.push('Root');
  const ns = 'Odin.Schemas.' + nsParts.map(p => p.charAt(0).toUpperCase() + p.slice(1).replace(/-(\w)/g, (_, c) => c.toUpperCase())).join('.');

  lines.push(`// ${title} - Generated by odin-codegen`);
  lines.push('using System;');
  lines.push('using System.Collections.Generic;');
  lines.push('using System.ComponentModel.DataAnnotations;');
  lines.push('');
  lines.push(`namespace ${ns};`);
  lines.push('');

  // Collect local type names so cross-schema refs fall back to object
  const localTypes = new Set<string>();
  for (const [typeName, schemaType] of parsed.types) {
    if (schemaType.fields.size === 1 && schemaType.fields.has('_composition')) continue;
    localTypes.add(typeNameToInterface(typeName));
  }

  for (const [typeName, schemaType] of parsed.types) {
    if (schemaType.fields.size === 1 && schemaType.fields.has('_composition')) continue;
    const resolved = resolveType(typeName, schemaType, allSchemas);
    lines.push(generateClass(resolved, localTypes));
    lines.push('');
  }

  return lines.join('\n');
}
