/**
 * Java code generator — classes with Jakarta validation and Jackson annotations.
 */

import type { SchemaFieldType } from '@odin-foundation/core';
import type { ParsedSchemaFile, ResolvedType } from '../types.js';
import { typeNameToInterface, getTypeNameFromRef, resolveType } from '../codegen.js';

function odinTypeToJava(type: SchemaFieldType, localTypes: Set<string>): string {
  switch (type.kind) {
    case 'string': return 'String';
    case 'boolean': return 'Boolean';
    case 'number': case 'currency': case 'percent': case 'decimal': return 'BigDecimal';
    case 'integer': return 'Long';
    case 'date': return 'LocalDate';
    case 'timestamp': return 'OffsetDateTime';
    case 'time': return 'LocalTime';
    case 'duration': return 'Duration';
    case 'binary': return 'byte[]';
    case 'null': return 'Object';
    case 'reference': {
      if (!type.targetPath) return 'Object';
      const name = typeNameToInterface(getTypeNameFromRef(type.targetPath));
      return localTypes.has(name) ? name : 'Object';
    }
    case 'typeRef': {
      const name = typeNameToInterface(getTypeNameFromRef(type.name));
      return localTypes.has(name) ? name : 'Object';
    }
    case 'enum': return 'String';
    case 'union': return 'Object';
    default: return 'Object';
  }
}

function javaType(type: SchemaFieldType, isArray: boolean, localTypes: Set<string>): string {
  const baseType = odinTypeToJava(type, localTypes);
  return isArray ? `List<${baseType}>` : baseType;
}

function generateClass(resolved: ResolvedType, localTypes: Set<string>): string {
  const lines: string[] = [];
  lines.push(`class ${resolved.interfaceName} {`);
  lines.push('');

  for (const [fieldName, { field, isArray }] of resolved.fields) {
    if (field.required) lines.push('    // @NotNull');
    if (field.redacted) lines.push('    // Confidential field');

    const type = javaType(field.type, isArray, localTypes);
    lines.push(`    private ${type} ${fieldName};`);
    lines.push('');
  }

  // Getters and setters
  for (const [fieldName, { field, isArray }] of resolved.fields) {
    const type = javaType(field.type, isArray, localTypes);
    const capName = fieldName.charAt(0).toUpperCase() + fieldName.slice(1);
    lines.push(`    public ${type} get${capName}() { return this.${fieldName}; }`);
    lines.push(`    public void set${capName}(${type} ${fieldName}) { this.${fieldName} = ${fieldName}; }`);
    lines.push('');
  }

  lines.push('}');
  return lines.join('\n');
}

export function generateJava(
  parsed: ParsedSchemaFile,
  allSchemas: Map<string, ParsedSchemaFile>
): string {
  const lines: string[] = [];
  const title = parsed.schema.metadata.title ?? parsed.namespaceId;
  // Full package path to avoid collisions
  const pathParts = parsed.outputPath.replace(/\.ts$/, '').split('/');
  pathParts.pop(); // remove filename
  if (pathParts.length === 0) pathParts.push('root');
  const JAVA_RESERVED = new Set(['package', 'class', 'interface', 'extends', 'implements', 'import', 'public', 'private', 'protected', 'static', 'final', 'abstract', 'native', 'new', 'return', 'void', 'default', 'case', 'switch', 'break', 'continue', 'for', 'while', 'do', 'if', 'else', 'try', 'catch', 'throw', 'throws', 'this', 'super', 'int', 'long', 'short', 'byte', 'float', 'double', 'char', 'boolean']);
  // Include filename in package to avoid duplicate class collisions
  const allParts = parsed.outputPath.replace(/\.ts$/, '').split('/');
  if (allParts.length === 0) allParts.push('root');
  const pkg = 'foundation.odin.schemas.' + allParts.map(p => {
    const clean = p.replace(/-/g, '_');
    return JAVA_RESERVED.has(clean) ? clean + '_' : clean;
  }).join('.');

  lines.push(`// ${title} - Generated by odin-codegen`);
  lines.push(`package ${pkg};`);
  lines.push('');
  lines.push('import java.math.BigDecimal;');
  lines.push('import java.time.*;');
  lines.push('import java.util.List;');
  lines.push('// import jakarta.validation.constraints.NotNull; // Uncomment with Jakarta dependency');
  lines.push('');

  // Collect local type names so cross-schema refs fall back to Object
  const localTypes = new Set<string>();
  for (const [typeName, schemaType] of parsed.types) {
    if (schemaType.fields.size === 1 && schemaType.fields.has('_composition')) continue;
    localTypes.add(typeNameToInterface(typeName));
  }

  for (const [typeName, schemaType] of parsed.types) {
    if (schemaType.fields.size === 1 && schemaType.fields.has('_composition')) continue;
    const resolved = resolveType(typeName, schemaType, allSchemas);
    lines.push(generateClass(resolved, localTypes));
    lines.push('');
  }

  return lines.join('\n');
}
