/**
 * Python code generator — dataclasses with type hints.
 */

import type { SchemaFieldType } from '@odin-foundation/core';
import type { ParsedSchemaFile, ResolvedType } from '../types.js';
import { typeNameToInterface, getTypeNameFromRef, resolveType, toSafePropertyName } from '../codegen.js';

function toSnakeCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/[-]/g, '_').toLowerCase();
}

function odinTypeToPython(type: SchemaFieldType, localTypes: Set<string>): string {
  switch (type.kind) {
    case 'string': return 'str';
    case 'boolean': return 'bool';
    case 'number': case 'currency': case 'percent': case 'decimal': return 'Decimal';
    case 'integer': return 'int';
    case 'date': return 'date';
    case 'timestamp': return 'datetime';
    case 'time': return 'time';
    case 'duration': return 'str';
    case 'binary': return 'bytes';
    case 'null': return 'None';
    case 'reference': {
      if (!type.targetPath) return 'Any';
      const name = typeNameToInterface(getTypeNameFromRef(type.targetPath));
      return localTypes.has(name) ? name : 'Any';
    }
    case 'typeRef': {
      const name = typeNameToInterface(getTypeNameFromRef(type.name));
      return localTypes.has(name) ? name : 'Any';
    }
    case 'enum': return 'str';
    case 'union': return 'Any';
    default: return 'Any';
  }
}

function pythonType(type: SchemaFieldType, required: boolean, nullable: boolean, isArray: boolean, localTypes: Set<string>): string {
  const baseType = odinTypeToPython(type, localTypes);
  if (isArray) return required ? `list[${baseType}]` : `list[${baseType}] | None`;
  if (nullable) return `${baseType} | None`;
  if (!required) return `${baseType} | None`;
  return baseType;
}

function generateClass(resolved: ResolvedType, localTypes: Set<string>): string {
  const lines: string[] = [];
  lines.push(`@dataclass`);
  lines.push(`class ${resolved.interfaceName}:`);

  if (resolved.fields.size === 0) {
    lines.push('    pass');
    return lines.join('\n');
  }

  // Required fields first, then optional
  const required: [string, { field: any; isArray: boolean }][] = [];
  const optional: [string, { field: any; isArray: boolean }][] = [];

  for (const [fieldName, info] of resolved.fields) {
    if (info.field.required) required.push([fieldName, info]);
    else optional.push([fieldName, info]);
  }

  for (const [fieldName, { field, isArray }] of required) {
    const pyName = toSnakeCase(fieldName);
    const type = pythonType(field.type, true, field.nullable, isArray, localTypes);
    if (field.redacted) lines.push(`    # Confidential field`);
    lines.push(`    ${pyName}: ${type}`);
  }

  for (const [fieldName, { field, isArray }] of optional) {
    const pyName = toSnakeCase(fieldName);
    const type = pythonType(field.type, false, field.nullable, isArray, localTypes);
    if (field.redacted) lines.push(`    # Confidential field`);
    lines.push(`    ${pyName}: ${type} = None`);
  }

  return lines.join('\n');
}

export function generatePython(
  parsed: ParsedSchemaFile,
  allSchemas: Map<string, ParsedSchemaFile>
): string {
  const lines: string[] = [];
  const title = parsed.schema.metadata.title ?? parsed.namespaceId;

  lines.push(`# ${title} - Generated by odin-codegen`);
  lines.push('from __future__ import annotations');
  lines.push('from dataclasses import dataclass');
  lines.push('from datetime import date, datetime, time');
  lines.push('from decimal import Decimal');
  lines.push('from typing import Any');
  lines.push('');

  // Collect local type names so cross-schema refs fall back to Any
  const localTypes = new Set<string>();
  for (const [typeName, schemaType] of parsed.types) {
    if (schemaType.fields.size === 1 && schemaType.fields.has('_composition')) continue;
    localTypes.add(typeNameToInterface(typeName));
  }

  for (const [typeName, schemaType] of parsed.types) {
    if (schemaType.fields.size === 1 && schemaType.fields.has('_composition')) continue;
    const resolved = resolveType(typeName, schemaType, allSchemas);
    lines.push(generateClass(resolved, localTypes));
    lines.push('');
    lines.push('');
  }

  return lines.join('\n');
}
