/**
 * Ruby code generator — classes with attr_accessor and validation.
 */

import type { SchemaFieldType } from '@odin-foundation/core';
import type { ParsedSchemaFile, ResolvedType } from '../types.js';
import { typeNameToInterface, getTypeNameFromRef, resolveType } from '../codegen.js';

function toSnakeCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/[-]/g, '_').toLowerCase();
}

function generateClass(resolved: ResolvedType): string {
  const lines: string[] = [];
  const className = resolved.interfaceName;
  lines.push(`  class ${className}`);

  const attrs: string[] = [];
  for (const [fieldName] of resolved.fields) {
    attrs.push(toSnakeCase(fieldName));
  }

  if (attrs.length > 0) {
    lines.push(`    attr_accessor ${attrs.map(a => `:${a}`).join(', ')}`);
    lines.push('');
  }

  // Initialize
  lines.push('    def initialize(**kwargs)');
  for (const [fieldName, { field, isArray }] of resolved.fields) {
    const rbName = toSnakeCase(fieldName);
    const defaultVal = isArray ? '[]' : 'nil';
    lines.push(`      @${rbName} = kwargs[:${rbName}] || ${defaultVal}`);
  }
  lines.push('    end');
  lines.push('');

  // Validate
  const requiredFields = [...resolved.fields.entries()].filter(([, { field }]) => field.required);
  if (requiredFields.length > 0) {
    lines.push('    def validate!');
    for (const [fieldName, { field }] of requiredFields) {
      const rbName = toSnakeCase(fieldName);
      lines.push(`      raise ArgumentError, "${rbName} is required" if @${rbName}.nil?`);
    }
    lines.push('      true');
    lines.push('    end');
    lines.push('');
  }

  // to_hash
  lines.push('    def to_hash');
  lines.push('      {');
  for (const [fieldName] of resolved.fields) {
    const rbName = toSnakeCase(fieldName);
    lines.push(`        ${rbName}: @${rbName},`);
  }
  lines.push('      }.compact');
  lines.push('    end');

  lines.push('  end');
  return lines.join('\n');
}

export function generateRuby(
  parsed: ParsedSchemaFile,
  allSchemas: Map<string, ParsedSchemaFile>
): string {
  const lines: string[] = [];
  const title = parsed.schema.metadata.title ?? parsed.namespaceId;
  // Full path module nesting to avoid class collisions between schemas
  const allParts = parsed.outputPath.replace(/\.ts$/, '').split('/');
  const modParts = allParts.map(p => {
    const clean = p.replace(/-/g, '_');
    return clean.charAt(0).toUpperCase() + clean.slice(1).replace(/_(\w)/g, (_, c: string) => c.toUpperCase());
  });

  lines.push(`# ${title} - Generated by odin-codegen`);
  lines.push(`module Odin`);
  const indent = '  ';
  for (let i = 0; i < modParts.length; i++) {
    lines.push(`${indent.repeat(i + 1)}module ${modParts[i]}`);
  }
  lines.push('');

  const classIndent = indent.repeat(modParts.length + 1);
  for (const [typeName, schemaType] of parsed.types) {
    if (schemaType.fields.size === 1 && schemaType.fields.has('_composition')) continue;
    const resolved = resolveType(typeName, schemaType, allSchemas);
    // Indent class body
    const classCode = generateClass(resolved).split('\n').map(l => classIndent + l).join('\n');
    lines.push(classCode);
    lines.push('');
  }

  for (let i = modParts.length - 1; i >= 0; i--) {
    lines.push(`${indent.repeat(i + 1)}end`);
  }
  lines.push('end');

  return lines.join('\n');
}
