/**
 * Rust code generator — structs with serde derives.
 */

import type { SchemaFieldType } from '@odin-foundation/core';
import type { ParsedSchemaFile, ResolvedType } from '../types.js';
import { typeNameToInterface, getTypeNameFromRef, resolveType } from '../codegen.js';

const RUST_KEYWORDS = new Set([
  'type', 'self', 'super', 'crate', 'mod', 'fn', 'struct', 'enum', 'trait', 'impl',
  'pub', 'use', 'let', 'mut', 'const', 'static', 'ref', 'return', 'if', 'else',
  'match', 'for', 'while', 'loop', 'break', 'continue', 'move', 'box', 'where',
  'async', 'await', 'dyn', 'abstract', 'become', 'do', 'final', 'macro', 'override',
  'priv', 'typeof', 'unsized', 'virtual', 'yield', 'try', 'union', 'as', 'in',
]);

function toSnakeCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/[-]/g, '_').toLowerCase();
}

function safeRustFieldName(name: string): string {
  const snake = toSnakeCase(name);
  return RUST_KEYWORDS.has(snake) ? `r#${snake}` : snake;
}

function safeRustStructName(name: string): string {
  // Avoid shadowing std types
  const RESERVED_TYPES = new Set(['Option', 'Result', 'Box', 'Vec', 'String', 'Error', 'Self']);
  return RESERVED_TYPES.has(name) ? name + 'Type' : name;
}

function odinTypeToRust(type: SchemaFieldType, localTypes: Set<string>): string {
  switch (type.kind) {
    case 'string': return 'String';
    case 'boolean': return 'bool';
    case 'number': case 'currency': case 'percent': case 'decimal': return 'f64';
    case 'integer': return 'i64';
    case 'date': case 'timestamp': case 'time': case 'duration': return 'String';
    case 'binary': return 'Vec<u8>';
    case 'null': return 'Option<()>';
    case 'reference': {
      if (!type.targetPath) return 'serde_json::Value';
      const name = safeRustStructName(typeNameToInterface(getTypeNameFromRef(type.targetPath)));
      // Use Box for local type refs to handle potential self-referential types
      return localTypes.has(name) ? `Box<${name}>` : 'serde_json::Value';
    }
    case 'typeRef': {
      const name = safeRustStructName(typeNameToInterface(getTypeNameFromRef(type.name)));
      return localTypes.has(name) ? `Box<${name}>` : 'serde_json::Value';
    }
    case 'enum': return 'String';
    case 'union': return 'serde_json::Value';
    default: return 'serde_json::Value';
  }
}

function rustType(type: SchemaFieldType, required: boolean, nullable: boolean, isArray: boolean, localTypes: Set<string>): string {
  const baseType = odinTypeToRust(type, localTypes);
  // Strip Box for Vec items — only direct refs need Box (for potential recursion)
  const vecType = baseType.startsWith('Box<') ? baseType.slice(4, -1) : baseType;
  if (isArray) return required ? `Vec<${vecType}>` : `Option<Vec<${vecType}>>`;
  if (nullable || !required) return `Option<${baseType}>`;
  return baseType;
}

function generateStruct(resolved: ResolvedType, localTypes: Set<string>): string {
  const lines: string[] = [];
  const structName = safeRustStructName(resolved.interfaceName);
  lines.push('#[derive(Debug, Clone, Default, Serialize, Deserialize)]');
  lines.push(`pub struct ${structName} {`);

  for (const [fieldName, { field, isArray }] of resolved.fields) {
    const rustName = safeRustFieldName(fieldName);
    const type = rustType(field.type, field.required, field.nullable, isArray, localTypes);

    // Always add serde rename to map camelCase field to the safe rust name
    lines.push(`    #[serde(rename = "${fieldName}")]`);
    if (!field.required) {
      lines.push(`    #[serde(skip_serializing_if = "Option::is_none")]`);
    }
    if (field.redacted) {
      lines.push(`    // Confidential field`);
    }
    lines.push(`    pub ${rustName}: ${type},`);
  }

  lines.push('}');
  return lines.join('\n');
}

export function generateRust(
  parsed: ParsedSchemaFile,
  allSchemas: Map<string, ParsedSchemaFile>
): string {
  const lines: string[] = [];
  const title = parsed.schema.metadata.title ?? parsed.namespaceId;

  lines.push(`//! ${title} - Generated by odin-codegen`);
  lines.push('');
  lines.push('use serde::{Deserialize, Serialize};');
  lines.push('');

  // Collect local type names (with safe naming) so cross-schema refs fall back to serde_json::Value
  const localTypes = new Set<string>();
  for (const [typeName, schemaType] of parsed.types) {
    if (schemaType.fields.size === 1 && schemaType.fields.has('_composition')) continue;
    localTypes.add(safeRustStructName(typeNameToInterface(typeName)));
  }

  for (const [typeName, schemaType] of parsed.types) {
    if (schemaType.fields.size === 1 && schemaType.fields.has('_composition')) continue;
    const resolved = resolveType(typeName, schemaType, allSchemas);
    lines.push(generateStruct(resolved, localTypes));
    lines.push('');
  }

  return lines.join('\n');
}
